### ISSUE TITLE
Infinite timeout (-1) does not work: 'Invalid command option'

### ISSUE THREAD

**Issue by rkubis** [rh-messaging/cli-netlite#8]
**Try:**

    dotnet cli-netlite-core-receiver.dll --timeout -1

or

    dotnet cli-netlite-core-sender.dll --timeout -1

**Comment by kornys** [comment]
@rkubis just for sure, sender does not support infinite sending with -1 in other clients, right?

**Comment by rkubis** [comment]
I saw that cli-java clients have infinite sending, but I think that we do not need it.
